
<item>
<title>[COLOR silver][B] DEPT. Q 1º TEMPORADA [/COLOR][/B][COLOR yellow]  FULL HD  [B][/COLOR][/B]</title>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:6bead3fceb394c3b1bbc57f7d41436b73e1dbc67</link>
<thumbnail>https://media.themoviedb.org/t/p/original/uKoAaTUGMMtbk0BTn1JsNKw9oej.jpg</thumbnail>
<fanart></fanart>
<info>Carl, um ex-detetive de primeira linha, é atormentado pela culpa após um ataque que deixou seu parceiro paralisado e outro policial morto. Em seu retorno ao trabalho, Carl é designado para um caso arquivado que consumirá sua vida.</info>
</item>
